"""Pre-built security questionnaire question banks.

Three question banks are provided, each mapping questions to Shasta check_ids
and control test IDs so the QuestionnaireEngine can auto-fill answers from
scan findings.

Question banks:
  - SIG_LITE_QUESTIONS: Shared Assessments SIG Lite (~80 questions)
  - CAIQ_QUESTIONS: Cloud Security Alliance CAIQ v4 (~80 questions)
  - COMMON_ENTERPRISE_QUESTIONS: Universal enterprise buyer questions (~40 questions)
"""

from __future__ import annotations

from shasta.questionnaire.engine import Question

# ---------------------------------------------------------------------------
# SIG Lite — Shared Assessments Standardized Information Gathering
# ---------------------------------------------------------------------------

SIG_LITE_QUESTIONS: list[Question] = [
    # --- Access Control (10 questions) ---
    Question(
        id="SIG-A.01.01",
        text="Is multi-factor authentication required for all users with access to sensitive data?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-user-mfa", "iam-root-mfa", "azure-conditional-access-mfa"],
        test_ids=["CT-IAM-002", "CT-IAM-003"],
        frameworks=["SOC 2 CC6.1", "ISO 27001 A.8.5", "HIPAA 164.312(d)"],
    ),
    Question(
        id="SIG-A.01.02",
        text=(
            "Does the organization enforce a password policy that meets"
            " industry standards (minimum length, complexity, rotation)?"
        ),
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-password-policy"],
        test_ids=["CT-IAM-001"],
        frameworks=["SOC 2 CC6.1", "ISO 27001 A.8.5"],
    ),
    Question(
        id="SIG-A.01.03",
        text="Are user permissions managed through groups or roles rather than direct assignment?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-no-direct-policies", "azure-rbac-least-privilege"],
        test_ids=["CT-IAM-004"],
        frameworks=["SOC 2 CC6.2", "ISO 27001 A.8.2"],
    ),
    Question(
        id="SIG-A.01.04",
        text="Is the principle of least privilege enforced for all user accounts?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=[
            "iam-overprivileged-user",
            "azure-rbac-least-privilege",
            "azure-privileged-roles",
        ],
        test_ids=["CT-IAM-005"],
        frameworks=["SOC 2 CC6.2", "ISO 27001 A.8.2"],
    ),
    Question(
        id="SIG-A.01.05",
        text="Are access keys and credentials rotated within defined timeframes (e.g., 90 days)?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-access-key-rotation", "azure-service-principal-hygiene"],
        test_ids=["CT-IAM-006"],
        frameworks=["SOC 2 CC6.3", "ISO 27001 A.8.5"],
    ),
    Question(
        id="SIG-A.01.06",
        text="Are periodic access reviews conducted (at least quarterly)?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-inactive-user", "azure-inactive-users"],
        test_ids=["CT-IAM-007"],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.3", "ISO 27001 A.8.2"],
    ),
    Question(
        id="SIG-A.01.07",
        text=(
            "Is the root/global administrator account secured with MFA"
            " and restricted from daily use?"
        ),
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-root-mfa", "iam-root-access-keys"],
        test_ids=["CT-IAM-002"],
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="SIG-A.01.08",
        text="Are inactive user accounts disabled or removed within 90 days of last activity?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-inactive-user", "azure-inactive-users"],
        test_ids=["CT-IAM-007"],
        frameworks=["SOC 2 CC6.3"],
    ),
    Question(
        id="SIG-A.01.09",
        text="Is there a documented access management policy?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.1", "ISO 27001 A.5.15"],
    ),
    Question(
        id="SIG-A.01.10",
        text="Are external/guest user accounts reviewed and restricted appropriately?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["azure-guest-access"],
        frameworks=["SOC 2 CC6.2", "ISO 27001 A.8.2"],
    ),
    # --- Asset Management (5 questions) ---
    Question(
        id="SIG-B.01.01",
        text="Does the organization maintain an inventory of all information assets?",
        category="Asset Management",
        expected_answer="yes_no",
        check_ids=["config-enabled", "azure-policy-compliance"],
        test_ids=["CT-MON-003"],
        policy_type="asset-management",
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.5.9"],
    ),
    Question(
        id="SIG-B.01.02",
        text="Is encryption at rest enabled for all data storage services?",
        category="Asset Management",
        expected_answer="yes_no",
        check_ids=[
            "s3-encryption-at-rest",
            "ebs-encryption-by-default",
            "ebs-volume-encrypted",
            "rds-encryption-at-rest",
            "azure-storage-encryption",
            "azure-disk-encryption",
            "azure-sql-tde",
        ],
        test_ids=["CT-DATA-001"],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24", "HIPAA 164.312(a)(2)(iv)"],
    ),
    Question(
        id="SIG-B.01.03",
        text="Are cloud resources tagged and classified according to data sensitivity?",
        category="Asset Management",
        expected_answer="yes_no",
        check_ids=["config-enabled"],
        policy_type="data-classification",
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.5.12"],
    ),
    Question(
        id="SIG-B.01.04",
        text="Is there a process for decommissioning assets when no longer needed?",
        category="Asset Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="asset-management",
        frameworks=["SOC 2 CC6.5", "ISO 27001 A.5.11"],
    ),
    Question(
        id="SIG-B.01.05",
        text="Are all production systems covered by automated configuration management?",
        category="Asset Management",
        expected_answer="yes_no",
        check_ids=["config-enabled", "azure-policy-compliance"],
        test_ids=["CT-MON-003"],
        frameworks=["SOC 2 CC8.1"],
    ),
    # --- Business Continuity (7 questions) ---
    Question(
        id="SIG-C.01.01",
        text="Are automated backups configured for all critical data stores?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[
            "s3-versioning",
            "rds-backup-enabled",
            "azure-storage-soft-delete",
        ],
        test_ids=["CT-DATA-004"],
        frameworks=["SOC 2 A1.2", "ISO 27001 A.8.13"],
    ),
    Question(
        id="SIG-C.01.02",
        text="Is there a documented business continuity plan (BCP)?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="business-continuity",
        frameworks=["SOC 2 A1.2", "ISO 27001 A.5.30"],
    ),
    Question(
        id="SIG-C.01.03",
        text="Is there a documented disaster recovery plan (DRP)?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="disaster-recovery",
        frameworks=["SOC 2 A1.2", "ISO 27001 A.5.30"],
    ),
    Question(
        id="SIG-C.01.04",
        text="Are recovery time objectives (RTO) and recovery point objectives (RPO) defined?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="disaster-recovery",
        frameworks=["SOC 2 A1.2", "ISO 27001 A.5.30"],
    ),
    Question(
        id="SIG-C.01.05",
        text="Are backup restoration tests performed at least annually?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="business-continuity",
        frameworks=["SOC 2 A1.2"],
    ),
    Question(
        id="SIG-C.01.06",
        text="Is data replicated across multiple availability zones or regions?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=["rds-backup-enabled", "s3-versioning"],
        frameworks=["SOC 2 A1.2", "ISO 27001 A.8.14"],
    ),
    Question(
        id="SIG-C.01.07",
        text="Has the BCP/DRP been tested within the last 12 months?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="business-continuity",
        frameworks=["SOC 2 A1.3"],
    ),
    # --- Change Management (7 questions) ---
    Question(
        id="SIG-D.01.01",
        text="Is an audit trail maintained for all changes to production infrastructure?",
        category="Change Management",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "azure-activity-log"],
        test_ids=["CT-MON-001"],
        frameworks=["SOC 2 CC8.1", "ISO 27001 A.8.32"],
    ),
    Question(
        id="SIG-D.01.02",
        text="Is resource configuration recording enabled (e.g., AWS Config, Azure Policy)?",
        category="Change Management",
        expected_answer="yes_no",
        check_ids=["config-enabled", "azure-policy-compliance"],
        test_ids=["CT-MON-003"],
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="SIG-D.01.03",
        text="Is there a formal change management policy?",
        category="Change Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1", "ISO 27001 A.8.32"],
    ),
    Question(
        id="SIG-D.01.04",
        text="Are code changes subject to peer review before deployment?",
        category="Change Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="SIG-D.01.05",
        text="Are production deployments authorized and logged?",
        category="Change Management",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "azure-activity-log"],
        test_ids=["CT-MON-001"],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="SIG-D.01.06",
        text="Is there a rollback procedure for failed deployments?",
        category="Change Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="SIG-D.01.07",
        text="Are emergency changes documented and reviewed post-implementation?",
        category="Change Management",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled"],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    # --- Data Security (8 questions) ---
    Question(
        id="SIG-E.01.01",
        text="Is data encrypted in transit using TLS 1.2 or higher?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=["s3-ssl-only", "azure-storage-https-only"],
        test_ids=["CT-DATA-002"],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24", "HIPAA 164.312(e)(1)"],
    ),
    Question(
        id="SIG-E.01.02",
        text="Is data encrypted at rest using industry-standard algorithms (AES-256)?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[
            "s3-encryption-at-rest",
            "ebs-encryption-by-default",
            "ebs-volume-encrypted",
            "rds-encryption-at-rest",
            "azure-storage-encryption",
            "azure-disk-encryption",
            "azure-sql-tde",
        ],
        test_ids=["CT-DATA-001"],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24", "HIPAA 164.312(a)(2)(iv)"],
    ),
    Question(
        id="SIG-E.01.03",
        text="Are all storage resources protected from unauthorized public access?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[
            "s3-public-access-block",
            "rds-no-public-access",
            "azure-sql-public-access",
        ],
        test_ids=["CT-DATA-003"],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.3"],
    ),
    Question(
        id="SIG-E.01.04",
        text="Is there a data classification policy defining sensitivity levels?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="data-classification",
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.5.12"],
    ),
    Question(
        id="SIG-E.01.05",
        text="Are database instances protected from direct public internet access?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=["rds-no-public-access", "azure-sql-public-access"],
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.20"],
    ),
    Question(
        id="SIG-E.01.06",
        text="Is versioning enabled on object storage to prevent accidental data loss?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=["s3-versioning", "azure-storage-soft-delete"],
        test_ids=["CT-DATA-004"],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="SIG-E.01.07",
        text="Is there a data retention and disposal policy?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="data-retention",
        frameworks=["SOC 2 CC6.5", "ISO 27001 A.8.10"],
    ),
    Question(
        id="SIG-E.01.08",
        text="Are encryption keys managed through a dedicated key management service?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=["azure-keyvault-config"],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24"],
    ),
    # --- Incident Management (7 questions) ---
    Question(
        id="SIG-F.01.01",
        text=(
            "Is a threat detection service (e.g., GuardDuty, Defender)"
            " enabled and actively monitoring?"
        ),
        category="Incident Management",
        expected_answer="yes_no",
        check_ids=["guardduty-enabled", "guardduty-no-active-findings", "azure-defender-enabled"],
        test_ids=["CT-MON-002"],
        frameworks=["SOC 2 CC7.2", "ISO 27001 A.5.25"],
    ),
    Question(
        id="SIG-F.01.02",
        text="Is there a documented incident response plan?",
        category="Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.3", "ISO 27001 A.5.24", "HIPAA 164.308(a)(6)"],
    ),
    Question(
        id="SIG-F.01.03",
        text="Are security incidents tracked and documented to resolution?",
        category="Incident Management",
        expected_answer="yes_no",
        check_ids=["guardduty-no-active-findings"],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.4", "ISO 27001 A.5.26"],
    ),
    Question(
        id="SIG-F.01.04",
        text="Is there an escalation procedure for critical security incidents?",
        category="Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.3"],
    ),
    Question(
        id="SIG-F.01.05",
        text="Are post-incident reviews conducted after security events?",
        category="Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.5", "ISO 27001 A.5.27"],
    ),
    Question(
        id="SIG-F.01.06",
        text="Are alerting rules configured for critical security events?",
        category="Incident Management",
        expected_answer="yes_no",
        check_ids=["azure-monitor-alerts", "guardduty-enabled"],
        frameworks=["SOC 2 CC7.2"],
    ),
    Question(
        id="SIG-F.01.07",
        text="Are affected parties notified within defined timeframes when a breach occurs?",
        category="Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.4", "HIPAA 164.408"],
    ),
    # --- Network Security (8 questions) ---
    Question(
        id="SIG-G.01.01",
        text=(
            "Are firewall rules or security groups configured to restrict"
            " inbound traffic to necessary ports only?"
        ),
        category="Network Security",
        expected_answer="yes_no",
        check_ids=[
            "sg-no-unrestricted-ingress",
            "sg-default-restricted",
            "azure-nsg-unrestricted-ingress",
            "azure-nsg-default-restricted",
        ],
        test_ids=["CT-NET-001"],
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.20"],
    ),
    Question(
        id="SIG-G.01.02",
        text="Is network flow logging enabled for all virtual networks?",
        category="Network Security",
        expected_answer="yes_no",
        check_ids=["vpc-flow-logs-enabled", "azure-vnet-flow-logs"],
        test_ids=["CT-NET-002"],
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.16"],
    ),
    Question(
        id="SIG-G.01.03",
        text="Is network segmentation implemented to isolate sensitive systems?",
        category="Network Security",
        expected_answer="yes_no",
        check_ids=["sg-default-restricted", "azure-nsg-default-restricted"],
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.22"],
    ),
    Question(
        id="SIG-G.01.04",
        text="Are default security groups/NSGs configured to deny all traffic?",
        category="Network Security",
        expected_answer="yes_no",
        check_ids=["sg-default-restricted", "azure-nsg-default-restricted"],
        frameworks=["SOC 2 CC6.6"],
    ),
    Question(
        id="SIG-G.01.05",
        text="Is SSH/RDP access restricted to specific IP ranges?",
        category="Network Security",
        expected_answer="yes_no",
        check_ids=["sg-no-unrestricted-ingress", "azure-nsg-unrestricted-ingress"],
        test_ids=["CT-NET-001"],
        frameworks=["SOC 2 CC6.6"],
    ),
    Question(
        id="SIG-G.01.06",
        text="Are web application firewalls (WAFs) deployed for public-facing applications?",
        category="Network Security",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.20"],
    ),
    Question(
        id="SIG-G.01.07",
        text="Is there a network security policy?",
        category="Network Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="network-security",
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.20"],
    ),
    Question(
        id="SIG-G.01.08",
        text="Are DDoS protection mechanisms in place for public-facing services?",
        category="Network Security",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.20"],
    ),
    # --- Risk Management (7 questions) ---
    Question(
        id="SIG-H.01.01",
        text="Does the organization maintain a risk register?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="risk-assessment",
        frameworks=["SOC 2 CC3.2", "ISO 27001 A.5.8"],
    ),
    Question(
        id="SIG-H.01.02",
        text="Is a formal risk assessment performed at least annually?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="risk-assessment",
        frameworks=["SOC 2 CC3.2", "ISO 27001 6.1.2"],
    ),
    Question(
        id="SIG-H.01.03",
        text="Are identified risks tracked with assigned owners and treatment plans?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="risk-assessment",
        frameworks=["SOC 2 CC3.2", "ISO 27001 A.5.8"],
    ),
    Question(
        id="SIG-H.01.04",
        text="Is there an information security policy approved by management?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC1.1", "ISO 27001 A.5.1"],
    ),
    Question(
        id="SIG-H.01.05",
        text="Are security roles and responsibilities formally defined?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC1.3", "ISO 27001 A.5.2"],
    ),
    Question(
        id="SIG-H.01.06",
        text="Is security awareness training provided to all employees?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="security-awareness",
        frameworks=["SOC 2 CC1.4", "ISO 27001 A.6.3"],
    ),
    Question(
        id="SIG-H.01.07",
        text="Is there a process for managing exceptions to security policies?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="risk-assessment",
        frameworks=["SOC 2 CC3.2"],
    ),
    # --- Vulnerability Management (7 questions) ---
    Question(
        id="SIG-I.01.01",
        text="Is vulnerability scanning performed continuously or at regular intervals?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=["inspector-enabled", "inspector-critical-findings"],
        test_ids=["CT-VULN-001"],
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.8"],
    ),
    Question(
        id="SIG-I.01.02",
        text="Are critical and high vulnerabilities remediated within defined SLAs?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=["inspector-critical-findings"],
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.8"],
    ),
    Question(
        id="SIG-I.01.03",
        text="Is there a vulnerability management policy?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vulnerability-management",
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.8"],
    ),
    Question(
        id="SIG-I.01.04",
        text="Are software dependencies scanned for known vulnerabilities?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=["inspector-enabled"],
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="SIG-I.01.05",
        text="Is there a process for tracking and applying security patches?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=["inspector-critical-findings"],
        policy_type="vulnerability-management",
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.8"],
    ),
    Question(
        id="SIG-I.01.06",
        text="Are penetration tests performed at least annually?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vulnerability-management",
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.8"],
    ),
    Question(
        id="SIG-I.01.07",
        text="Is a Software Bill of Materials (SBOM) maintained for production applications?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC7.1"],
    ),
    # --- Vendor Management (5 questions) ---
    Question(
        id="SIG-J.01.01",
        text="Is there a vendor risk management program?",
        category="Vendor Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2", "ISO 27001 A.5.19"],
    ),
    Question(
        id="SIG-J.01.02",
        text="Are third-party vendors assessed for security practices before engagement?",
        category="Vendor Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2", "ISO 27001 A.5.20"],
    ),
    Question(
        id="SIG-J.01.03",
        text=(
            "Are Business Associate Agreements (BAAs) in place with"
            " vendors handling sensitive data?"
        ),
        category="Vendor Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2", "HIPAA 164.308(b)"],
    ),
    Question(
        id="SIG-J.01.04",
        text="Are vendor security assessments reviewed periodically (at least annually)?",
        category="Vendor Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2", "ISO 27001 A.5.22"],
    ),
    Question(
        id="SIG-J.01.05",
        text="Is there a process for terminating vendor access when the relationship ends?",
        category="Vendor Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2"],
    ),
    # --- Logging & Monitoring (8 questions) ---
    Question(
        id="SIG-K.01.01",
        text="Are audit logs enabled for all cloud management plane actions?",
        category="Logging & Monitoring",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "azure-activity-log"],
        test_ids=["CT-MON-001"],
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.15"],
    ),
    Question(
        id="SIG-K.01.02",
        text="Are logs stored with integrity protection (e.g., log file validation)?",
        category="Logging & Monitoring",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled"],
        test_ids=["CT-MON-001"],
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.15"],
    ),
    Question(
        id="SIG-K.01.03",
        text="Are log retention periods defined and enforced (minimum 90 days)?",
        category="Logging & Monitoring",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "azure-activity-log"],
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="SIG-K.01.04",
        text="Are alerting rules configured for suspicious or anomalous activity?",
        category="Logging & Monitoring",
        expected_answer="yes_no",
        check_ids=["guardduty-enabled", "azure-defender-enabled", "azure-monitor-alerts"],
        test_ids=["CT-MON-002"],
        frameworks=["SOC 2 CC7.2"],
    ),
    Question(
        id="SIG-K.01.05",
        text="Is centralized log management in place across all environments?",
        category="Logging & Monitoring",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "azure-activity-log"],
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.15"],
    ),
    Question(
        id="SIG-K.01.06",
        text="Is resource configuration recording enabled (AWS Config / Azure Policy)?",
        category="Logging & Monitoring",
        expected_answer="yes_no",
        check_ids=["config-enabled", "azure-policy-compliance"],
        test_ids=["CT-MON-003"],
        frameworks=["SOC 2 CC7.1", "CC8.1"],
    ),
    Question(
        id="SIG-K.01.07",
        text="Are network flow logs collected and retained?",
        category="Logging & Monitoring",
        expected_answer="yes_no",
        check_ids=["vpc-flow-logs-enabled", "azure-vnet-flow-logs"],
        test_ids=["CT-NET-002"],
        frameworks=["SOC 2 CC6.6", "CC7.1"],
    ),
    Question(
        id="SIG-K.01.08",
        text="Is there a logging and monitoring policy?",
        category="Logging & Monitoring",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="logging-monitoring",
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.15"],
    ),
]


# ---------------------------------------------------------------------------
# CAIQ — Cloud Security Alliance Consensus Assessments Initiative Questionnaire
# ---------------------------------------------------------------------------

CAIQ_QUESTIONS: list[Question] = [
    # --- Application Security (8 questions) ---
    Question(
        id="CAIQ-AIS-01",
        text=(
            "Are application security risks identified and managed"
            " throughout the development lifecycle?"
        ),
        category="Application Security",
        expected_answer="yes_no",
        check_ids=["inspector-enabled"],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1", "ISO 27001 A.8.25"],
    ),
    Question(
        id="CAIQ-AIS-02",
        text="Is secure coding training provided to development staff?",
        category="Application Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="security-awareness",
        frameworks=["SOC 2 CC1.4", "ISO 27001 A.8.28"],
    ),
    Question(
        id="CAIQ-AIS-03",
        text="Are automated security testing tools (SAST/DAST) integrated into the CI/CD pipeline?",
        category="Application Security",
        expected_answer="yes_no",
        check_ids=["inspector-enabled"],
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="CAIQ-AIS-04",
        text="Is code peer-reviewed before merging to production branches?",
        category="Application Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="CAIQ-AIS-05",
        text="Are third-party libraries and dependencies monitored for vulnerabilities?",
        category="Application Security",
        expected_answer="yes_no",
        check_ids=["inspector-enabled", "inspector-critical-findings"],
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="CAIQ-AIS-06",
        text="Is input validation enforced on all user-facing interfaces?",
        category="Application Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="change-management",
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.28"],
    ),
    Question(
        id="CAIQ-AIS-07",
        text=(
            "Are application logs capturing security-relevant events"
            " (authentication, authorization failures)?"
        ),
        category="Application Security",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "azure-activity-log"],
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="CAIQ-AIS-08",
        text="Is there a process for managing and remediating application-level vulnerabilities?",
        category="Application Security",
        expected_answer="yes_no",
        check_ids=["inspector-critical-findings"],
        policy_type="vulnerability-management",
        frameworks=["SOC 2 CC7.1"],
    ),
    # --- Audit & Assurance (7 questions) ---
    Question(
        id="CAIQ-AAC-01",
        text="Are independent audits conducted at least annually (e.g., SOC 2 Type II)?",
        category="Audit & Assurance",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC4.1", "ISO 27001 A.5.35"],
    ),
    Question(
        id="CAIQ-AAC-02",
        text="Is compliance evidence collected and retained in an auditable format?",
        category="Audit & Assurance",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "config-enabled"],
        test_ids=["CT-MON-001", "CT-MON-003"],
        frameworks=["SOC 2 CC4.1"],
    ),
    Question(
        id="CAIQ-AAC-03",
        text="Are control tests performed regularly to validate control effectiveness?",
        category="Audit & Assurance",
        expected_answer="yes_no",
        check_ids=["config-enabled"],
        frameworks=["SOC 2 CC4.1"],
    ),
    Question(
        id="CAIQ-AAC-04",
        text="Is there a process for tracking and remediating audit findings?",
        category="Audit & Assurance",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="risk-assessment",
        frameworks=["SOC 2 CC4.2"],
    ),
    Question(
        id="CAIQ-AAC-05",
        text="Are audit logs tamper-resistant and stored separately from production systems?",
        category="Audit & Assurance",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled"],
        frameworks=["SOC 2 CC7.1", "ISO 27001 A.8.15"],
    ),
    Question(
        id="CAIQ-AAC-06",
        text="Can audit trails demonstrate the state of compliance at any point in time?",
        category="Audit & Assurance",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "config-enabled", "azure-activity-log"],
        frameworks=["SOC 2 CC4.1"],
    ),
    Question(
        id="CAIQ-AAC-07",
        text=(
            "Are compliance certifications and attestation reports"
            " shared with customers upon request?"
        ),
        category="Audit & Assurance",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC4.1"],
    ),
    # --- Business Continuity (7 questions) ---
    Question(
        id="CAIQ-BCR-01",
        text="Is there a business continuity management program?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="business-continuity",
        frameworks=["SOC 2 A1.2", "ISO 27001 A.5.30"],
    ),
    Question(
        id="CAIQ-BCR-02",
        text="Are backups encrypted and tested regularly?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=["rds-backup-enabled", "s3-versioning", "rds-encryption-at-rest"],
        frameworks=["SOC 2 A1.2", "ISO 27001 A.8.13"],
    ),
    Question(
        id="CAIQ-BCR-03",
        text="Are service dependencies and single points of failure documented?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="business-continuity",
        frameworks=["SOC 2 A1.2"],
    ),
    Question(
        id="CAIQ-BCR-04",
        text="Is disaster recovery tested at least annually?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="disaster-recovery",
        frameworks=["SOC 2 A1.3"],
    ),
    Question(
        id="CAIQ-BCR-05",
        text="Are RTO and RPO targets defined and validated through testing?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="disaster-recovery",
        frameworks=["SOC 2 A1.2"],
    ),
    Question(
        id="CAIQ-BCR-06",
        text="Is data retained across multiple geographic regions for resilience?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=["s3-versioning", "rds-backup-enabled"],
        frameworks=["SOC 2 A1.2"],
    ),
    Question(
        id="CAIQ-BCR-07",
        text="Are critical systems designed with high availability (multi-AZ or multi-region)?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=["rds-backup-enabled"],
        frameworks=["SOC 2 A1.2"],
    ),
    # --- Change Control (7 questions) ---
    Question(
        id="CAIQ-CCC-01",
        text="Is there a formal change management process for production environments?",
        category="Change Control",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled"],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1", "ISO 27001 A.8.32"],
    ),
    Question(
        id="CAIQ-CCC-02",
        text="Are all changes to production logged and attributable to an individual?",
        category="Change Control",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "azure-activity-log"],
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="CAIQ-CCC-03",
        text="Is there separation of duties between development and production environments?",
        category="Change Control",
        expected_answer="yes_no",
        check_ids=["iam-overprivileged-user", "azure-privileged-roles"],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="CAIQ-CCC-04",
        text="Are changes tested in a staging environment before production deployment?",
        category="Change Control",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="CAIQ-CCC-05",
        text="Is there an approval workflow for changes affecting security controls?",
        category="Change Control",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="CAIQ-CCC-06",
        text="Are infrastructure changes managed through infrastructure-as-code (IaC)?",
        category="Change Control",
        expected_answer="yes_no",
        check_ids=["config-enabled"],
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="CAIQ-CCC-07",
        text="Is there a process for emergency changes with post-hoc review?",
        category="Change Control",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    # --- Data Security (8 questions) ---
    Question(
        id="CAIQ-DSP-01",
        text="Is data classified according to sensitivity and regulatory requirements?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="data-classification",
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.5.12"],
    ),
    Question(
        id="CAIQ-DSP-02",
        text="Are data encryption standards enforced for data at rest?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[
            "s3-encryption-at-rest",
            "ebs-encryption-by-default",
            "rds-encryption-at-rest",
            "azure-storage-encryption",
            "azure-disk-encryption",
            "azure-sql-tde",
        ],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24"],
    ),
    Question(
        id="CAIQ-DSP-03",
        text="Is data encrypted in transit for all internal and external communications?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=["s3-ssl-only", "azure-storage-https-only"],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24"],
    ),
    Question(
        id="CAIQ-DSP-04",
        text="Are data retention and deletion policies documented and enforced?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="data-retention",
        frameworks=["SOC 2 CC6.5", "ISO 27001 A.8.10"],
    ),
    Question(
        id="CAIQ-DSP-05",
        text="Is customer data isolated from other tenants in multi-tenant environments?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="CAIQ-DSP-06",
        text="Are data processing agreements in place with all sub-processors?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2", "ISO 27001 A.5.20"],
    ),
    Question(
        id="CAIQ-DSP-07",
        text="Is there a process for responding to data subject access requests (DSARs)?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="data-retention",
        frameworks=["SOC 2 P6.1"],
    ),
    Question(
        id="CAIQ-DSP-08",
        text="Are database backups encrypted and access-controlled?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=["rds-encryption-at-rest", "rds-backup-enabled"],
        frameworks=["SOC 2 CC6.7"],
    ),
    # --- Encryption & Key Management (7 questions) ---
    Question(
        id="CAIQ-EKM-01",
        text="Is a key management service (KMS) used for managing encryption keys?",
        category="Encryption & Key Management",
        expected_answer="yes_no",
        check_ids=["azure-keyvault-config"],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24"],
    ),
    Question(
        id="CAIQ-EKM-02",
        text="Are encryption keys rotated according to a defined schedule?",
        category="Encryption & Key Management",
        expected_answer="yes_no",
        check_ids=["azure-keyvault-config"],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="CAIQ-EKM-03",
        text="Is TLS 1.2 or higher enforced for all external connections?",
        category="Encryption & Key Management",
        expected_answer="yes_no",
        check_ids=["s3-ssl-only", "azure-storage-https-only"],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="CAIQ-EKM-04",
        text="Are encryption keys stored separately from the data they protect?",
        category="Encryption & Key Management",
        expected_answer="yes_no",
        check_ids=["azure-keyvault-config"],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="CAIQ-EKM-05",
        text="Is access to encryption keys restricted to authorized personnel only?",
        category="Encryption & Key Management",
        expected_answer="yes_no",
        check_ids=["azure-keyvault-config", "iam-overprivileged-user"],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="CAIQ-EKM-06",
        text="Are hardware security modules (HSMs) used for sensitive key operations?",
        category="Encryption & Key Management",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="CAIQ-EKM-07",
        text="Is there a documented cryptographic policy?",
        category="Encryption & Key Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="encryption",
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24"],
    ),
    # --- Governance & Risk (7 questions) ---
    Question(
        id="CAIQ-GRC-01",
        text="Is there an information security governance framework in place?",
        category="Governance & Risk",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC1.1", "ISO 27001 A.5.1"],
    ),
    Question(
        id="CAIQ-GRC-02",
        text="Are information security policies reviewed and approved at least annually?",
        category="Governance & Risk",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC1.1", "ISO 27001 A.5.1"],
    ),
    Question(
        id="CAIQ-GRC-03",
        text="Is there a designated security officer or team responsible for security?",
        category="Governance & Risk",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC1.3", "ISO 27001 A.5.2"],
    ),
    Question(
        id="CAIQ-GRC-04",
        text="Is security awareness training mandatory for all employees?",
        category="Governance & Risk",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="security-awareness",
        frameworks=["SOC 2 CC1.4", "ISO 27001 A.6.3"],
    ),
    Question(
        id="CAIQ-GRC-05",
        text="Is there a process for identifying and complying with applicable regulations?",
        category="Governance & Risk",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC2.2", "ISO 27001 A.5.31"],
    ),
    Question(
        id="CAIQ-GRC-06",
        text=(
            "Are risk assessments performed before deploying new services"
            " or making significant changes?"
        ),
        category="Governance & Risk",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="risk-assessment",
        frameworks=["SOC 2 CC3.2"],
    ),
    Question(
        id="CAIQ-GRC-07",
        text="Is board or executive oversight provided for the security program?",
        category="Governance & Risk",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC1.2"],
    ),
    # --- Identity & Access Management (8 questions) ---
    Question(
        id="CAIQ-IAM-01",
        text="Is multi-factor authentication enforced for all administrative access?",
        category="Identity & Access Management",
        expected_answer="yes_no",
        check_ids=["iam-user-mfa", "iam-root-mfa", "azure-conditional-access-mfa"],
        test_ids=["CT-IAM-002", "CT-IAM-003"],
        frameworks=["SOC 2 CC6.1", "ISO 27001 A.8.5"],
    ),
    Question(
        id="CAIQ-IAM-02",
        text="Is role-based access control (RBAC) implemented across all systems?",
        category="Identity & Access Management",
        expected_answer="yes_no",
        check_ids=["iam-no-direct-policies", "azure-rbac-least-privilege", "azure-aks-rbac"],
        test_ids=["CT-IAM-004"],
        frameworks=["SOC 2 CC6.2"],
    ),
    Question(
        id="CAIQ-IAM-03",
        text="Are privileged accounts inventoried and subject to enhanced monitoring?",
        category="Identity & Access Management",
        expected_answer="yes_no",
        check_ids=["iam-overprivileged-user", "azure-privileged-roles"],
        test_ids=["CT-IAM-005"],
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="CAIQ-IAM-04",
        text="Is user provisioning and de-provisioning managed through a formal process?",
        category="Identity & Access Management",
        expected_answer="yes_no",
        check_ids=["iam-inactive-user", "azure-inactive-users"],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.2", "CC6.3"],
    ),
    Question(
        id="CAIQ-IAM-05",
        text="Are service accounts and API keys managed with the same rigor as user accounts?",
        category="Identity & Access Management",
        expected_answer="yes_no",
        check_ids=["iam-access-key-rotation", "azure-service-principal-hygiene"],
        test_ids=["CT-IAM-006"],
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="CAIQ-IAM-06",
        text="Is single sign-on (SSO) implemented for cloud service access?",
        category="Identity & Access Management",
        expected_answer="yes_no",
        check_ids=["azure-conditional-access-mfa"],
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="CAIQ-IAM-07",
        text="Are access reviews performed at least quarterly for privileged accounts?",
        category="Identity & Access Management",
        expected_answer="yes_no",
        check_ids=["iam-inactive-user", "azure-inactive-users"],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.3"],
    ),
    Question(
        id="CAIQ-IAM-08",
        text="Is there an identity and access management policy?",
        category="Identity & Access Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.1", "ISO 27001 A.5.15"],
    ),
    # --- Infrastructure Security (8 questions) ---
    Question(
        id="CAIQ-IVS-01",
        text=(
            "Are network security controls (firewalls, security groups)"
            " configured to restrict traffic?"
        ),
        category="Infrastructure Security",
        expected_answer="yes_no",
        check_ids=[
            "sg-no-unrestricted-ingress",
            "sg-default-restricted",
            "azure-nsg-unrestricted-ingress",
            "azure-nsg-default-restricted",
        ],
        test_ids=["CT-NET-001"],
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.20"],
    ),
    Question(
        id="CAIQ-IVS-02",
        text="Is network traffic monitored through flow logs or packet capture?",
        category="Infrastructure Security",
        expected_answer="yes_no",
        check_ids=["vpc-flow-logs-enabled", "azure-vnet-flow-logs"],
        test_ids=["CT-NET-002"],
        frameworks=["SOC 2 CC6.6"],
    ),
    Question(
        id="CAIQ-IVS-03",
        text="Are compute resources (VMs, containers) hardened according to security baselines?",
        category="Infrastructure Security",
        expected_answer="yes_no",
        check_ids=["azure-aks-rbac", "inspector-enabled"],
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.9"],
    ),
    Question(
        id="CAIQ-IVS-04",
        text="Is storage access controlled through bucket policies, ACLs, or equivalent?",
        category="Infrastructure Security",
        expected_answer="yes_no",
        check_ids=["s3-public-access-block", "azure-storage-encryption"],
        test_ids=["CT-DATA-003"],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="CAIQ-IVS-05",
        text="Are database services configured to deny public access by default?",
        category="Infrastructure Security",
        expected_answer="yes_no",
        check_ids=["rds-no-public-access", "azure-sql-public-access"],
        frameworks=["SOC 2 CC6.6"],
    ),
    Question(
        id="CAIQ-IVS-06",
        text=(
            "Is network segmentation enforced between production,"
            " staging, and development environments?"
        ),
        category="Infrastructure Security",
        expected_answer="yes_no",
        check_ids=["sg-default-restricted", "azure-nsg-default-restricted"],
        frameworks=["SOC 2 CC6.6"],
    ),
    Question(
        id="CAIQ-IVS-07",
        text="Are container orchestration platforms secured with RBAC and network policies?",
        category="Infrastructure Security",
        expected_answer="yes_no",
        check_ids=["azure-aks-rbac"],
        frameworks=["SOC 2 CC6.6"],
    ),
    Question(
        id="CAIQ-IVS-08",
        text="Is there an infrastructure security hardening standard?",
        category="Infrastructure Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="network-security",
        frameworks=["SOC 2 CC6.6", "ISO 27001 A.8.9"],
    ),
    # --- Security Incident Management (7 questions) ---
    Question(
        id="CAIQ-SEF-01",
        text="Is continuous threat detection enabled across all cloud environments?",
        category="Security Incident Management",
        expected_answer="yes_no",
        check_ids=["guardduty-enabled", "azure-defender-enabled"],
        test_ids=["CT-MON-002"],
        frameworks=["SOC 2 CC7.2"],
    ),
    Question(
        id="CAIQ-SEF-02",
        text="Is there a documented security incident response plan?",
        category="Security Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.3", "ISO 27001 A.5.24"],
    ),
    Question(
        id="CAIQ-SEF-03",
        text="Are security incidents classified by severity with defined response times?",
        category="Security Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.3"],
    ),
    Question(
        id="CAIQ-SEF-04",
        text="Is there a process for notifying affected customers of security incidents?",
        category="Security Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.4"],
    ),
    Question(
        id="CAIQ-SEF-05",
        text="Are forensic investigation capabilities available for security incidents?",
        category="Security Incident Management",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "vpc-flow-logs-enabled"],
        frameworks=["SOC 2 CC7.4"],
    ),
    Question(
        id="CAIQ-SEF-06",
        text="Are lessons learned from incidents used to improve security controls?",
        category="Security Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.5", "ISO 27001 A.5.27"],
    ),
    Question(
        id="CAIQ-SEF-07",
        text=(
            "Are incident response procedures tested through tabletop exercises at least annually?"
        ),
        category="Security Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.3"],
    ),
    # --- Supply Chain & Vendor (6 questions) ---
    Question(
        id="CAIQ-STA-01",
        text="Are software supply chain risks assessed and managed?",
        category="Supply Chain & Vendor",
        expected_answer="yes_no",
        check_ids=["inspector-enabled", "inspector-critical-findings"],
        frameworks=["SOC 2 CC9.2"],
    ),
    Question(
        id="CAIQ-STA-02",
        text="Is a software bill of materials (SBOM) maintained?",
        category="Supply Chain & Vendor",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="CAIQ-STA-03",
        text="Are vendor security practices assessed before onboarding?",
        category="Supply Chain & Vendor",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2", "ISO 27001 A.5.19"],
    ),
    Question(
        id="CAIQ-STA-04",
        text="Are vendor security assessments conducted periodically?",
        category="Supply Chain & Vendor",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2", "ISO 27001 A.5.22"],
    ),
    Question(
        id="CAIQ-STA-05",
        text="Is there a process for evaluating vendor sub-processors?",
        category="Supply Chain & Vendor",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2"],
    ),
    Question(
        id="CAIQ-STA-06",
        text="Are contractual security requirements included in vendor agreements?",
        category="Supply Chain & Vendor",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2", "ISO 27001 A.5.20"],
    ),
]


# ---------------------------------------------------------------------------
# Common Enterprise Buyer Questions
# ---------------------------------------------------------------------------

COMMON_ENTERPRISE_QUESTIONS: list[Question] = [
    Question(
        id="ENT-001",
        text="Do you have a current SOC 2 Type II report?",
        category="Compliance",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2"],
    ),
    Question(
        id="ENT-002",
        text="Is data encrypted at rest and in transit?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[
            "s3-encryption-at-rest",
            "ebs-encryption-by-default",
            "rds-encryption-at-rest",
            "s3-ssl-only",
            "azure-storage-encryption",
            "azure-disk-encryption",
            "azure-storage-https-only",
        ],
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.8.24"],
    ),
    Question(
        id="ENT-003",
        text="Do you have an incident response plan?",
        category="Incident Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC7.3"],
    ),
    Question(
        id="ENT-004",
        text="How do you manage access for terminated employees?",
        category="Access Control",
        expected_answer="text",
        check_ids=["iam-inactive-user", "azure-inactive-users"],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.3"],
    ),
    Question(
        id="ENT-005",
        text="Do you perform regular penetration testing?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=["inspector-network-reachability"],
        policy_type="vulnerability-management",
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="ENT-006",
        text="Do you have a vulnerability management program?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=["inspector-enabled", "inspector-critical-findings"],
        policy_type="vulnerability-management",
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="ENT-007",
        text="How do you handle data deletion requests?",
        category="Data Security",
        expected_answer="text",
        check_ids=[],
        policy_type="data-retention",
        frameworks=["SOC 2 P6.1"],
    ),
    Question(
        id="ENT-008",
        text="Is multi-factor authentication required for all users?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-user-mfa", "iam-root-mfa", "azure-conditional-access-mfa"],
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="ENT-009",
        text="Do you have a business continuity and disaster recovery plan?",
        category="Business Continuity",
        expected_answer="yes_no",
        check_ids=["rds-backup-enabled", "s3-versioning"],
        policy_type="business-continuity",
        frameworks=["SOC 2 A1.2"],
    ),
    Question(
        id="ENT-010",
        text="Are your cloud environments monitored for security threats?",
        category="Monitoring",
        expected_answer="yes_no",
        check_ids=["guardduty-enabled", "azure-defender-enabled"],
        frameworks=["SOC 2 CC7.2"],
    ),
    Question(
        id="ENT-011",
        text="Do you maintain audit logs for all system access and changes?",
        category="Logging",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled", "azure-activity-log", "config-enabled"],
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="ENT-012",
        text="Is access to production systems based on the principle of least privilege?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=[
            "iam-overprivileged-user",
            "iam-no-direct-policies",
            "azure-rbac-least-privilege",
        ],
        frameworks=["SOC 2 CC6.2"],
    ),
    Question(
        id="ENT-013",
        text="Do you have a formal change management process?",
        category="Change Management",
        expected_answer="yes_no",
        check_ids=["cloudtrail-enabled"],
        policy_type="change-management",
        frameworks=["SOC 2 CC8.1"],
    ),
    Question(
        id="ENT-014",
        text="Are employee background checks performed before granting system access?",
        category="Human Resources",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC1.4"],
    ),
    Question(
        id="ENT-015",
        text="Do you provide security awareness training to all employees?",
        category="Human Resources",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="security-awareness",
        frameworks=["SOC 2 CC1.4", "ISO 27001 A.6.3"],
    ),
    Question(
        id="ENT-016",
        text="Where is customer data stored geographically?",
        category="Data Security",
        expected_answer="text",
        check_ids=[],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="ENT-017",
        text="Do you support single sign-on (SSO) integration?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["azure-conditional-access-mfa"],
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="ENT-018",
        text="Is there a risk management program in place?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="risk-assessment",
        frameworks=["SOC 2 CC3.2"],
    ),
    Question(
        id="ENT-019",
        text="Do you have a vendor risk management program?",
        category="Vendor Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2"],
    ),
    Question(
        id="ENT-020",
        text="Are network firewalls and segmentation in place?",
        category="Network Security",
        expected_answer="yes_no",
        check_ids=[
            "sg-no-unrestricted-ingress",
            "sg-default-restricted",
            "azure-nsg-unrestricted-ingress",
        ],
        frameworks=["SOC 2 CC6.6"],
    ),
    Question(
        id="ENT-021",
        text="Is there an acceptable use policy for employees?",
        category="Governance",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="acceptable-use",
        frameworks=["SOC 2 CC1.4", "ISO 27001 A.5.10"],
    ),
    Question(
        id="ENT-022",
        text="How long are audit logs retained?",
        category="Logging",
        expected_answer="text",
        check_ids=["cloudtrail-enabled"],
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="ENT-023",
        text="Do you perform periodic access reviews?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-inactive-user", "azure-inactive-users"],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.3"],
    ),
    Question(
        id="ENT-024",
        text="Is your infrastructure hosted in a SOC 2 certified data center?",
        category="Infrastructure",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC6.4"],
    ),
    Question(
        id="ENT-025",
        text="Do you have cyber insurance?",
        category="Risk Management",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC3.2"],
    ),
    Question(
        id="ENT-026",
        text="Is there a process for securely disposing of hardware and media?",
        category="Asset Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="asset-management",
        frameworks=["SOC 2 CC6.5", "ISO 27001 A.7.14"],
    ),
    Question(
        id="ENT-027",
        text="Are API endpoints authenticated and rate-limited?",
        category="Application Security",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="ENT-028",
        text="Do you support customer-managed encryption keys (BYOK)?",
        category="Encryption",
        expected_answer="yes_no",
        check_ids=["azure-keyvault-config"],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="ENT-029",
        text="Is there separation of duties for critical operations?",
        category="Access Control",
        expected_answer="yes_no",
        check_ids=["iam-overprivileged-user", "azure-privileged-roles"],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="ENT-030",
        text="Do you have a privacy policy that complies with applicable regulations?",
        category="Privacy",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 P1.1"],
    ),
    Question(
        id="ENT-031",
        text="Are database connections encrypted?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=["rds-encryption-at-rest", "azure-sql-tde"],
        frameworks=["SOC 2 CC6.7"],
    ),
    Question(
        id="ENT-032",
        text="Is there a formal information security policy?",
        category="Governance",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="information-security",
        frameworks=["SOC 2 CC1.1", "ISO 27001 A.5.1"],
    ),
    Question(
        id="ENT-033",
        text="Do you have a data classification scheme?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="data-classification",
        frameworks=["SOC 2 CC6.7", "ISO 27001 A.5.12"],
    ),
    Question(
        id="ENT-034",
        text="Are passwords stored using industry-standard hashing algorithms?",
        category="Application Security",
        expected_answer="yes_no",
        check_ids=["iam-password-policy"],
        frameworks=["SOC 2 CC6.1"],
    ),
    Question(
        id="ENT-035",
        text="Is there a process for reporting security concerns or violations?",
        category="Governance",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="incident-response",
        frameworks=["SOC 2 CC2.3"],
    ),
    Question(
        id="ENT-036",
        text="Are subprocessors and their locations disclosed?",
        category="Vendor Management",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="vendor-management",
        frameworks=["SOC 2 CC9.2"],
    ),
    Question(
        id="ENT-037",
        text="Can you provide evidence of your last penetration test?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=[],
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="ENT-038",
        text="Is there a process for patch management with defined SLAs?",
        category="Vulnerability Management",
        expected_answer="yes_no",
        check_ids=["inspector-critical-findings"],
        policy_type="vulnerability-management",
        frameworks=["SOC 2 CC7.1"],
    ),
    Question(
        id="ENT-039",
        text="Do you support data export in a standard format upon contract termination?",
        category="Data Security",
        expected_answer="yes_no",
        check_ids=[],
        policy_type="data-retention",
        frameworks=["SOC 2 CC6.5"],
    ),
    Question(
        id="ENT-040",
        text="Is there a documented onboarding and offboarding process for employees?",
        category="Human Resources",
        expected_answer="yes_no",
        check_ids=["iam-inactive-user"],
        policy_type="access-management",
        frameworks=["SOC 2 CC6.2", "CC6.3"],
    ),
]


# Convenience mapping for questionnaire selection
QUESTIONNAIRE_BANKS: dict[str, list[Question]] = {
    "sig_lite": SIG_LITE_QUESTIONS,
    "caiq": CAIQ_QUESTIONS,
    "enterprise": COMMON_ENTERPRISE_QUESTIONS,
}
